AUTHOR:
  NAME: 'Hacker'
  GITHUB: 'torvalds'

BLOG:
  NAME: 'Hacker Blog'
  TMPDIR: '/tmp'
  TMPNAME: 'WIngTmp'
  PORT: 8080
  HOST: '127.0.0.1'
  INDEX_ARTICLE_NUMBER: 7
  SORT_ARTICLE_BY: 'create'

CONFIG:
  CONFIG_FILE: 'starfish.config.yaml'
  DIR_CONFIG_FILE: '.wdconfig.yaml'
  IGNORE_FILE: '.ignore'

STYLE:
  THEMEDIR: '@themes'
  THEME: 'white-card'
  THEME_CONFIG_FILE: 'theme.config.yaml'

SERVE:
  HOST: '0.0.0.0'
  PORT: '8080'

MAPPING:
  '@image': '/static/image/'
  '@root-asset': '/'
  '@demo': '/demo/'

LANG: 'zh-CN'
